name       : mozc
version    : 2.23.2815.102
release    : 2
source     :
    - https://gitlab.com/fcitx/mozc/repository/dad94584ea5012110ad1d204e433964243a1639d/archive.tar.bz2 : e38457e63a7fa8d62d87b4f8b3e89fe5f6939d92e3c4fd287a93358375693892
    - git|https://chromium.googlesource.com/external/gyp.git : e87d37d6bce611abed35e854d5ae1a401e9ce04c
    - https://github.com/hiroyuki-komatsu/japanese-usage-dictionary/archive/e5b3425575734c323e1d947009dd74709437b684.tar.gz : 0b6efee0eebac2c1a8eeea333278aa40fcef7846bba9a379962c6e567e7e3dc1
    - https://download.fcitx-im.org/fcitx-mozc/fcitx-mozc-icon.tar.gz : e1da3026bd79f8c5b1dc07080309f9568934a829271f4ab71850cb8088956d81
license    : BSD-3-Clause
component  :
    - desktop.core
    - ^fcitx-mozc : desktop.core
    - ^ibus-mozc : desktop.core
summary    :
    - Japanese Input Method for Linux
    - ^fcitx-mozc : Mozc engine for Fcitx
    - ^ibus-mozc : Mozc engine for IBus
description: |
    Mozc is a Japanese Input Method Editor (IME) for Linux that provides support for Fcitx or IBus.
builddeps  :
    - pkgconfig(fcitx)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(protobuf)
    - pkgconfig(Qt5Core)
    - pkgconfig(zinnia)
    - llvm-clang
rundeps    :
    - ^fcitx-mozc :
        - fcitx
        - mozc
    - ^ibus-mozc :
        - mozc
patterns   :
    - ^fcitx-mozc :
        - /usr/lib/fcitx
        - /usr/share/fcitx
    - ^ibus-mozc :
        - /usr/lib/ibus-mozc
        - /usr/share/ibus
setup      : |
    %patch -p1 < $pkgfiles/protobuf-370.patch
    %patch -p1 < $pkgfiles/new-era.patch
    rm -rf src/unix/fcitx5
    pushd ..
    ln -s mozc-* mozc
    ln -s $sources/gyp.git gyp
    tar xf $sources/e5b3425575734c323e1d947009dd74709437b684.tar.gz
    ln -s japanese-usage-dictionary-* japanese_usage_dictionary
    tar xf $sources/fcitx-mozc-icon.tar.gz

    for src in gyp japanese_usage_dictionary; do
        rmdir mozc/src/third_party/$src
        ln -sr $src mozc/src/third_party/$src
    done

    popd
    GYP_DEFINES="server_dir=/usr/lib64/mozc
        ibus_mozc_path=/usr/lib64/ibus-mozc/ibus-engine-mozc
        use_libprotobuf=1 use_libzinnia=1" \
    python2 src/build_mozc.py gyp --target_platform=Linux
build      : |
    pushd mozc
    targets="
        server/server.gyp:mozc_server
        gui/gui.gyp:mozc_tool
        unix/fcitx/fcitx.gyp:fcitx-mozc
        unix/ibus/ibus.gyp:ibus_mozc
        renderer/renderer.gyp:mozc_renderer"
    python2 src/build_mozc.py build -c Release $targets
install    : |
    pushd mozc/src
    install -d $installdir/usr/lib/{mozc,fcitx}
    pushd out_linux/Release
    install -Dm00755 mozc_server $installdir/usr/lib/mozc
    install -Dm00755 mozc_tool $installdir/usr/lib/mozc
    install -Dm00644 fcitx-mozc.so $installdir/usr/lib/fcitx
    mv ibus_mozc ibus-engine-mozc
    for bin in ibus-engine-mozc; do
        install -Dm00755 $bin $installdir/usr/lib/ibus-mozc/$bin
    done
    for bin in mozc_renderer mozc_server mozc_tool; do
        install -Dm00755 $bin $installdir/usr/lib/mozc/$bin
    done
    for xml in gen/unix/ibus/mozc.xml; do
        install -Dm00644 $xml $installdir/usr/share/ibus/component/${xml##*/}
    done
    popd
    pushd data/images/unix
    cp ime_product_icon_opensource-32.png product_icon.png
    for icon in *.png; do
        install -Dm00644 $icon $installdir/usr/share/ibus-mozc/${icon#ui-}
    done
    popd
    install -Dm00644 unix/fcitx/fcitx-mozc.conf $installdir/usr/share/fcitx/addon/fcitx-mozc.conf
    install -Dm00644 unix/fcitx/mozc.conf $installdir/usr/share/fcitx/inputmethod/mozc.conf

    for dotmo in out_linux/Release/gen/unix/fcitx/po/*.mo; do
        filename=$(basename $dotmo)
        lang=${filename/.mo/}
        install -Dm00644 $dotmo $installdir/usr/share/locale/$lang/LC_MESSAGES/fcitx-mozc.mo
    done
    popd

    install -d $installdir/usr/share/fcitx/mozc/icon
    install -m00644 fcitx-mozc-icons/mozc.png $installdir/usr/share/fcitx/mozc/icon/mozc.png
    install -m00644 fcitx-mozc-icons/mozc-alpha_full.png $installdir/usr/share/fcitx/mozc/icon/mozc-alpha_full.png
    install -m00644 fcitx-mozc-icons/mozc-alpha_half.png $installdir/usr/share/fcitx/mozc/icon/mozc-alpha_half.png
    install -m00644 fcitx-mozc-icons/mozc-direct.png $installdir/usr/share/fcitx/mozc/icon/mozc-direct.png
    install -m00644 fcitx-mozc-icons/mozc-hiragana.png $installdir/usr/share/fcitx/mozc/icon/mozc-hiragana.png
    install -m00644 fcitx-mozc-icons/mozc-katakana_full.png $installdir/usr/share/fcitx/mozc/icon/mozc-katakana_full.png
    install -m00644 fcitx-mozc-icons/mozc-katakana_half.png $installdir/usr/share/fcitx/mozc/icon/mozc-katakana_half.png
    install -m00644 fcitx-mozc-icons/mozc-dictionary.png $installdir/usr/share/fcitx/mozc/icon/mozc-dictionary.png
    install -m00644 fcitx-mozc-icons/mozc-properties.png $installdir/usr/share/fcitx/mozc/icon/mozc-properties.png
    install -m00644 fcitx-mozc-icons/mozc-tool.png $installdir/usr/share/fcitx/mozc/icon/mozc-tool.png
